POST http://localhost:5000/db/add-to-db HTTP/1.1
Content-Type: application/json

{
    "model": 2,
    "data": {
        "uid":"123346",
        "name":"Vedvardhan",
        "email":"ved@gmail.com",
        "photoURL":"https://be.com"
    }
}

###
POST http://localhost:5000/db/get-from-db HTTP/1.1
Content-Type: application/json

{
    "model": 2,
    "filterData": {
        "uid":"123346"
    }
}

